version: '3'
services:
  app:
    restart: always
    container_name: vhmp_server
    image: anokhadocker/vhmp-server:1.0
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - '27017:27017'
    volumes:
      - '/mnt/nissan/db:/data/db'
